### ISSUE TITLE
Consider storing aggregate id and event id as `BINARY(16)` on MySQL, instead of `VARCHAR(36)`

### ISSUE THREAD

**Issue by Ocramius** [EventSaucePHP/DoctrineMessageRepository#12]
Currently, the `MySQLDoctrineMessageRepository` attempts to store messages with `VARCHAR(36)` as value:

https://github.com/EventSaucePHP/DoctrineMessageRepository/blob/6f325cc4e780849a0ad8189fa56d8493858e0347/tests/setup-mysql-schema.php#L9-L11

This is obviously OK for playing around with the event store as a start, but when millions of messages start being stored, it really becomes a storage problem.

In practice, I believe that consumers can and likely will replace the `MySQLDoctrineMessageRepository` as soon as their applications grow, but the out-of-the-box example should probably use `BINARY(16)`, which is the preferred format for storing a UUID in MySQL (insert rant about mysql not having proper custom types here).

**Comment by frankdejonge** [comment]
I totally missed this, @Ocramius, my apologies. I'm definitely open to changing the base here. Perhaps we can turn the implementation into something that allows for these types of adaptations out of the box. Interfaces to supply the base SQL and parameters for the queries could open this up to be extended in the exact way you describe.

**Comment by frankdejonge** [comment]
Fixed in the new incarnation of this package:

https://packagist.org/packages/eventsauce/message-repository-for-doctrine
https://packagist.org/packages/eventsauce/message-repository-for-doctrine-v2
