### ISSUE TITLE
Changelog of table changes

### ISSUE THREAD

**Issue by christian-kolb** [EventSaucePHP/DoctrineMessageRepository#4]
Recently you've added the `aggregate_root_version` to the table.
Is there a way to see this except looking though the commits since the last release?

If not it would be great to have a changelog. Even if it's just in the global README of this project 🙂

**Comment by frankdejonge** [comment]
I'll make sure to add a changelog.md file 👍

**Comment by driesvints** [comment]
The changelog has been updated as well as all GitHub releases.
