### ISSUE TITLE
Add message storage DDL to documentation

### ISSUE THREAD

**Issue by yourwebmaker** [EventSaucePHP/DoctrineMessageRepository#8]
The required schema definition can't be found anywhere other than in the tests (https://github.com/EventSaucePHP/DoctrineMessageRepository/blob/master/tests/setup-mysql-schema.php)

Probably adding a simple DDL on the README file would solve.

What do you think guys?

I'm ready to push my first PR =)

**Comment by driesvints** [comment]
Feel free to PR this 👍

**Comment by driesvints** [comment]
Ah I just saw this was already added to the readme.
