### ISSUE TITLE
DoctrineMessageRepository attempts to store datetime in incorrect format for MySQL 8

### ISSUE THREAD

**Issue by niels-nijens** [EventSaucePHP/DoctrineMessageRepository#9]
When persisting a message with the current `DateTime` format the following error occurs:
```
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2020-11-09 12:50:22.601971+0000' for column 'time_of_recording' at row 1
```

The MySQL documentation states the following:
> As of MySQL 8.0.19, you can specify a time zone offset when inserting TIMESTAMP and DATETIME values into a table. The offset is appended to the date part of a datetime literal, with no intravening spaces, and uses the same format used for setting the time_zone system variable, with the following exceptions:
>
> **Source:** https://dev.mysql.com/doc/refman/8.0/en/datetime.html

This basically means MySQL 8 requires the timezone to be in a `+00:00` format.

The possible solutions I see are:

1. Changing `PointInTime::DATE_TIME_FORMAT` from `Y-m-d H:i:s.uO` to `Y-m-d H:i:s.uP` in the main package
2. Changing the datetime format in this library before persisting...

I'm happy to provide a pull request for either solution.

**Comment by niels-nijens** [comment]
My colleague already provided a pull request for solution 1: eventsaucephp/eventsauce#97 😅

**Comment by frankdejonge** [comment]
I've laid out some options to work around this for now: https://github.com/EventSaucePHP/EventSauce/issues/108#issuecomment-761768959

**Comment by driesvints** [comment]
Closing this one as this will be resolved in EventSauce v1
